{% set name = "setsimilaritysearch" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SetSimilaritySearch-{{ version }}.tar.gz
  sha256: 87eaa3c0fb522a7f88d2bae42a95ed30329fcc547e408382afcece11d5922c94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - SetSimilaritySearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ekzhu/SetSimilaritySearch
  summary: A Python library of set similarity search algorithms
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache

extra:
  recipe-maintainers:
    - sarthakpati
